bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_shopping_bag, name='view_shopping_bag'),
    path('add/<item_id>/', views.add_to_bag, name="add_to_bag"),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

brick_fitness/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('merch/', include('merch.urls')),
    path('subscriptions/', include('subscriptions.urls')),
    path('plans/', include('plans.urls')),
    path('profile/', include('user_profiles.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

merch/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_merch, name='merch'),
    path('<product_id>', views.merch_detail, name='product_detail'),
]

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings

from merch.models import Product


# Code institute code

class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = models.CharField(max_length=40, null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(max_digits=6, decimal_places=2, null=False, default=0)
    order_total = models.DecimalField(max_digits=10, decimal_places=2, null=False, default=0)
    grand_total = models.DecimalField(max_digits=10, decimal_places=2, null=False, default=0)

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total each time a line item is added,
        accounting for delivery costs.
        """
        self.order_total = self.lineitems.aggregate(Sum('lineitem_total'))['lineitem_total__sum'] or 0
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = self.order_total * settings.STANDARD_DELIVERY_PERCENTAGE / 100
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    order = models.ForeignKey(Order, null=False, blank=False, on_delete=models.CASCADE, related_name='lineitems')
    product = models.ForeignKey(Product, null=False, blank=False, on_delete=models.CASCADE)
    product_size = models.CharField(max_length=2, null=True, blank=True) # XS, S, M, L, XL
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(max_digits=6, decimal_places=2, null=False, blank=False, editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

merch/models.py
from django.db import models


# models
class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Color(models.Model):

    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Product(models.Model):
    category = models.ForeignKey(
        'Category', null=True, blank=True, on_delete=models.SET_NULL)
    color = models.ForeignKey(
        'Color', null=True, blank=True, on_delete=models.SET_NULL)
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    description = models.TextField(default="description_pending")
    price = models.DecimalField(max_digits=6, decimal_places=2, default=9900)
    has_sizes = models.BooleanField(default=False, null=True, blank=True)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)


    def __str__(self):
        return self.name

merch/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.db.models.functions import Lower
from django.db.models import Q

from .models import Product, Category, Color


# Create your views here.


def all_merch(request):
    """ This view returns the Merch page """
    products = Product.objects.all()
    all_colors = Color.objects.all()
    query = None
    categories = None
    sort = None
    direction = None
    color = None

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))
            if sortkey == 'category':
                sortkey = 'category__name'
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request,
                               "You didn't enter any search criteria!")
                return redirect(reverse('merch'))

            queries = Q(name__icontains=query) | Q(
                description__icontains=query)
            products = products.filter(queries)

        if 'color' in request.GET:
            colors = request.GET['color'].split(',')
            products = products.filter(color__name__in=colors)

    current_sorting = f'{sort}_{direction}'

    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
        'current_sorting': current_sorting,
        'all_colors': all_colors,
    }

    return render(request, 'merch/merch.html', context)


def merch_detail(request, product_id):
    """ This view returns the individual merch detail page """

    product = get_object_or_404(Product, pk=product_id)

    context = {
        'product': product,
    }
    return render(request, 'merch/merch_detail.html', context)

merch/templates/merch/merch.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'merch/css/merch.css' %}">
{% endblock %}


{% block content %}
    {% include 'merch/includes/merch-navbar-mobile.html'%}

    <div class="desktop-sorting d-none d-lg-inline">
        <h5 class="text-muted">Categories</h5>
        <ul class="pl-1">
            <li><a class="sorting-link" href="{% url 'merch' %}?category=workout_gear,accessories,hoodie-jumper,shoes,active_wear">All Categories</a></li>
            <li><a class="sorting-link" href="{% url 'merch' %}?category=active_wear">Activewear</a></li>
            <li><a class="sorting-link" href="{% url 'merch' %}?category=hoodie-jumper">Jumpers</a></li>
            <li><a class="sorting-link" href="{% url 'merch' %}?category=shoes">shoes</a></li>
            <li><a class="sorting-link" href="{% url 'merch' %}?category=accessories">Accessories</a></li>
            <li><a class="sorting-link" href="{% url 'merch' %}?category=workout_gear">Workout Gear</a></li>
        </ul>
        <hr class="sorting-hr">
        <h5 class="text-muted">Sort</h5>
        <ul class="pl-1">
            <li><a class="sorting-link" id="reset" href="#">Reset</a></li>
            <li><a class="sorting-link sort-button " id="price_asc" href="#">Price (Low < High)</a></li>
            <li><a class="sorting-link sort-button " id="name_asc" href="#">Name (A-Z)</a></li>
            <li><a class="sorting-link sort-button " id="name_desc" href="#">Name (Z-A)</a></li>
            <li><a class="sorting-link sort-button " id="price_desc" href="#">Price (High > Low)</a></li>
        </ul>
        <hr class="sorting-hr">
        <h5 class="text-muted">Colors</h5>
        <ul class="pl-1">
            {% for colors in all_colors %}
            <li><a class="sorting-link color-button" href="#"  id="{{ colors.name }}">{{ colors.name }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <section class="workout-bg merch-wrapper">
        <div class="text-muted mb-2 d-none d-lg-flex justify-content-between">
            <div class="button-sort-wrapper d-none d-lg-flex">
                <div class="in-row in-row-active d-flex " id="in-row-5">
                    <i class="fas fa-square-full"></i>
                    <i class="fas fa-square-full"></i>
                    <i class="fas fa-square-full"></i>
                    <i class="fas fa-square-full"></i>
                    <i class="fas fa-square-full"></i>
                </div>
                <div class="in-row  d-flex " id="in-row-6">
                    <i class="fas fa-square-full"></i>
                    <i class="fas fa-square-full"></i>
                    <i class="fas fa-square-full"></i>
                    <i class="fas fa-square-full"></i>
                    <i class="fas fa-square-full"></i>
                    <i class="fas fa-square-full"></i>
                </div>
            </div>
            <form method="GET" action="{% url 'merch' %}">
                <div class="input-group w-100">
                    <input class="form-control border border-black rounded-0 h-100" type="text" name="q" placeholder="Search our site">
                    <div class="input-group-append">
                        <button class="form-control btn btn-grn btn-black border border-black rounded-0 m-0 search-btn q-submit" type="submit">
                            <span class="icon">
                                <i class="fas fa-search"></i>
                            </span>
                        </button>
                    </div>
                </div>
            </form>
            <div>
                {{ products|length }} Products{% if search_term %} found for <strong class="mb-4">"{{ search_term }}"</strong>{% endif %}
            </div>
        </div>
        <hr class="sorting-hr w-100">
        <div class="row product-card-wrapper m-0">
            {% for product in products %}
                <div class="col-6 col-md-4  card-in-row-5  p-0 pb-1 card-merch">
                    <div class="product-card">
                        <div class="product-card-top">
                            {% if product.image %}
                                <a href="{% url 'product_detail' product.id %} ">
                                    <img class="img-fluid w-100" src="{{ product.image.url }}" alt="{{ product.name }}">
                                </a>
                            {% else %}
                                <a href="{% url 'product_detail' product.id %} ">
                                    <img class="img-fluid w-100" src="https://brick-fitness.s3.eu-west-2.amazonaws.com/media/noimage.png" alt="{{ product.name }}">
                                </a>
                            {% endif %}
                        </div>
                        <div class="product-card-bottom">
                            <p class="text-muted product-category">{{ product.category.friendly_name }}</p>
                            <p class="product-name">{{ product.name }}</p>
                            <p class="product-price">£{{ product.price }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </section>
{% endblock %}
{% block postloadjs %}
    {{ block.super }}
    <script src="{% static 'merch/js/merch.js' %}"></script>
{% endblock %}

merch/templates/merch/merch_detail.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'merch/css/merch-detail.css' %}">
{% endblock %}

{% block content %}
    <section class="workout-bg merch-wrapper">
        <div class="row m-0">
            <div class="col p-0">
                <h2 class="text-center text-muted mt-5 mb-5">Merch</h2>
            </div>
        </div>

        <div class="row product-card-wrapper m-0">
            <div class="col-10 offset-1 col-md-3 offset-md-2 ">
                <div class="">
                    {% if product.image %}
                            <a href="{{ product.image.url }}" target="_blank">
                                <img class="img-fluid w-75" src="{{ product.image.url }}" alt="{{ product.name }}">
                            </a>
                        {% else %}
                            <a href="">
                                <img class="img-fluid" src="https://brick-fitness.s3.eu-west-2.amazonaws.com/media/noimage.png" alt="{{ product.name }}">
                            </a>
                    {% endif %}
                </div>
            </div>
            <div class="col-12 col-md-5 offset-md-0">
                <p class="text-light"><strong>{{ product.name }}</strong></p>
                <p class="text-light">{{ product.price }}</p>
                <p>{{ product.description }}</p>
                {#       code institute provided code #}
                <form class="form" action="{% url 'add_to_bag' product.id %}" method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    {% with product.has_sizes as s %}
                                    {% if s %}
                                        <div class="col-12">
                                            <p><strong>Size:</strong></p>
                                            <select class="form-control rounded-0 w-25" name="product_size" id='id_product_size'>
                                                <option value="xs">XS</option>
                                                <option value="s">S</option>
                                                <option value="m" selected>M</option>
                                                <option value="l">L</option>
                                                <option value="xl">XL</option>
                                            </select>
                                        </div>
                                    {% endif %}
                                    <div class="col-12">
                                        <p class="mt-3"><strong>Quantity:</strong></p>
                                        <div class="form-group w-25">
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <button class="decrement-qty btn btn-grn  rounded-0 m-0 increment-btn"
                                                        data-item_id="{{ product.id }}" id="decrement-qty_{{ product.id }}">
                                                        <span class="icon">
                                                            <i class="fas fa-minus"></i>
                                                        </span>
                                                    </button>
                                                </div>
                                                <input class="form-control qty_input" type="number"
                                                    name="quantity" value="1" min="1" max="99"
                                                    data-item_id="{{ product.id }}"
                                                    id="id_qty_{{ product.id }}">
                                                <div class="input-group-append">
                                                    <button class="increment-qty btn btn-grn  rounded-0 m-0 increment-btn"
                                                        data-item_id="{{ product.id }}" id="increment-qty_{{ product.id }}">
                                                        <span class="icon">
                                                            <i class="fas fa-plus"></i>
                                                        </span>
                                                    </button>
                                                </div>
                                            </div>
                                        </div>

                                    <div class="">
                                        <a href="{% url 'merch' %}" class="btn btn-grn btn-extra rounded-0 mt-5 w-25 ">
                                            <span class="icon">
                                                <i class="fas fa-chevron-left"></i>
                                            </span>
                                            <span class="text-uppercase">Keep Shopping</span>
                                        </a>
                                        <input type="submit" class=" btn btn-grn w-25  rounded-0 text-uppercase mt-5 btn-extra" value="Add to Bag">
                                    </div>
                                    <input type="hidden" name="redirect_url" value="{{ request.path }}">
                                    {% endwith %}
                                </div>
                            </form>
                {# end of code institute code #}
            </div>
        </div>
    </section>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'merch/includes/quantity_input_script.html' %}
{% endblock %}